FROM cef_binary
RUN MKDIR c:/code/cefsharp
WORKDIR c:/code/cefsharp
RUN $env:Path = 'c:/Program Files/Git/bin/;' + $env:Path;setx /M PATH $env:Path;
RUN git clone https://github.com/cefsharp/CefSharp.git .
ARG CEFSHARP_BRANCH="cefsharp/63"
#This line and the one two below are due to waiting to use the new vs2017 compat build script
RUN cp build.ps1 ../
RUN git checkout $env:CEFSHARP_BRANCH;
RUN cp ../build.ps1 .
ARG CEFSHARP_VERSION=63.0.90
ARG CEF_VERSION_STR=auto
ARG CHROME_BRANCH=3239
ENV PACKAGE_SOURCE C:/code/cef-binary/cef-binary-master/NuGet
ADD cefsharp_set_versions_and_restore.ps1 c:/code/cefsharp
RUN ./cefsharp_set_versions_and_restore.ps1

#This next line is not used just skipped as a check at this point
ENV VS141COMNTOOLS C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build
RUN [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;./build.ps1 -Target vs2017 -Version $env:CEFSHARP_VERSION -AssemblyVersion $env:CEFSHARP_VERSION; 
RUN cp $env:PACKAGE_SOURCE/*.nupkg C:/code/cefsharp/nuget/
RUN Compress-Archive -Path C:/code/cefsharp/nuget/*.nupkg -CompressionLevel Fastest -DestinationPath C:\packages_cefsharp
